# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a44b37a69998da07bc91e34ed1ed49e0e25196a8783a776a08eb57754b245b5328308c00a96acab72f8f25c786e4a12a265ccd737f8b3a3ffd7198ee012234c

test:
  secret_key_base: 55c62f0523a8e33b578b20e2d5a3c6350694953e687aea4d16536d69d13b306b1b8877d7316a966b899c5511b457a75b51cda717b68b14b660650b614e16df2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
